name: Game Bot Auto
on:
  schedule:
    - cron: '*/15 * * * *' # প্রতি ১৫ মিনিট পর পর চলবে
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install requests
        run: pip install requests
      - name: Run script
        run: python script.py
      - name: Commit data
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add history.txt
          git commit -m "Update" || exit 0
          git push
